image: Visual Studio 2017
platform: x64

environment:
  
  matrix:
    - PYTHON_VERSION: "3.6"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"

clone_depth: 1
shallow_clone: true

# Do not build on tags (GitHub and BitBucket)
skip_tags: false

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: false

cache:
  - '%LOCALAPPDATA%\pip\Cache'
  - '%USERPROFILE%\.cache\pyemu'

init:
  - echo %PYTHON_VERSION% %CONDA_INSTALL_LOCN%

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - mkdir build
  - cd build
  - cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
  # - cmake --build .
  - ninja -j2
  # executable targets are automatically installed into bin; create artifact
  - cpack -G ZIP
  - cd ..

  - set PATH=%CONDA_INSTALL_LOCN%;%CONDA_INSTALL_LOCN%\scripts;%PATH%;
  - set PYTHONUNBUFFERED=1
  # for msinttypes and newer stuff

  - conda config --set always_yes true
  - conda update conda
  - conda update --all
  - conda config --set show_channel_urls yes
  - conda config --prepend channels conda-forge
  - call %CONDA_INSTALL_LOCN%\scripts\activate
  - conda info -a

  - conda install --yes python=%PYTHON_VERSION% pip numpy scipy pandas matplotlib nose
  - pip install coveralls pyshp nose-timer
  - pip install git+https://github.com/modflowpy/flopy.git@develop
  - pip install git+https://github.com/jtwhite79/pyemu.git@develop
  # Show the installed packages + versions
  - conda list
  - #git clone -b master --depth 1 https://github.com/jtwhite79/pestpp-opt_benchmarks
  - #git clone -b master --depth 1 https://github.com/jtwhite79/pestpp-ies_benchmarks

build: false

test_script:
  - #cd benchmarks
  - set PATH=%PATH%;..\..\..\test_bin\win;..\..\test_bin\win;
  - nosetests -v -w ./benchmarks basic_tests.py
<<<<<<< HEAD
  - nosetests -v -w ./benchmarks mou_tests.py
  - #set USE_INTEL="YES";
  - #nosetests -v -w ./benchmarks basic_tests.py
=======
>>>>>>> upstream_ayman/develop
  - #nosetests -v -w ./pestpp-ies_benchmarks ies_test.py
  - #nosetests -v -w ./pestpp-opt_benchmarks opt_test.py

after_test:
 - echo done

matrix:
  fast_finish: true

artifacts:
  - path: build\*.zip
    name: zip
